<?php
/**
 * Created by PhpStorm.
 * User: heyl
 * Date: 2019/5/25
 * Time: 14:02
 */

namespace app\admin\common;


use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //在公共控制器的初始化方法中，用来判断用户是否登录
        define('USER_ID',Session::get('user_id'));
    }

    //判断用户是否登录，在后台入口调用
    protected function isLogin(){
        //如果常量为null，表示没有登录
        if(is_null(USER_ID)){
            $this->error('未登录，无权访问~','login/index');
        }
    }

    //用户已经
    protected function alreadyLogin(){
        //如果常量为null，表示没有登录
        if(!is_null(USER_ID)){
            $this->error('请不要重复登录~','index/index');
        }
    }

}